// Mocks generated by Mockito 5.0.5 from annotations
// in dogceo_app/test/breed_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dogceo_app/data/api/api.dart' as _i3;
import 'package:dogceo_app/shared/result.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeResult<T> extends _i1.Fake implements _i2.Result<T> {}

/// A class which mocks [DogAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockDogAPI extends _i1.Mock implements _i3.DogAPI {
  MockDogAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<String>>> getBreeds(int? amountToGet) =>
      (super.noSuchMethod(Invocation.method(#getBreeds, [amountToGet]),
              returnValue: Future<_i2.Result<List<String>>>.value(
                  _FakeResult<List<String>>()))
          as _i4.Future<_i2.Result<List<String>>>);
  @override
  _i4.Future<_i2.Result<List<String>>> getImages(
          String? breedPath, int? count) =>
      (super.noSuchMethod(Invocation.method(#getImages, [breedPath, count]),
              returnValue: Future<_i2.Result<List<String>>>.value(
                  _FakeResult<List<String>>()))
          as _i4.Future<_i2.Result<List<String>>>);
}
