name: dogceo_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  mobx: ^2.0.1
  mobx_codegen: ^2.0.1+3
  flutter_mobx: ^2.0.0
  auto_route: ^1.0.2
  auto_route_generator: ^1.0.2
  share: ^2.0.1
  path_provider: ^2.0.1
  flutter_native_splash: ^1.1.8+4
  flutter_launcher_icons: ^0.9.0
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  lint: ^1.5.3
  mockito: ^5.0.5

# to run: flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFB648"
  image: "assets/graphics/paw.png"
  fullscreen: true

# to run: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/graphics/paw.png"

flutter:
  uses-material-design: true

  assets:
    - assets/graphics/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800

        
    
    
                                      